resources:
- ../../deployments/elasticsearch.yml
- ../../deployments/postgres.yml
- ../../deployments/redis.yml
- ../../deployments/smtp-server.yml
- ../../services/elasticsearch.yml
- ../../services/postgres.yml
- ../../services/redis.yml
- ../../services/smtp-server.yml
- ../../deployments/microservice-product-search-export.yml
- ../../deployments/microservice-product-search.yml
- ../../services/microservice-product-search-export.yml
- ../../services/microservice-product-search.yml
- ../../services/webserver-php-fpm.yml
- ../../deployments/webserver-php-fpm.yml
- ../../ingress.yml