resources:
- ../../deployments/elasticsearch.yml
- ../../deployments/postgres.yml
- ../../deployments/redis.yml
- ../../deployments/smtp-server.yml
- ../../services/elasticsearch.yml
- ../../services/postgres.yml
- ../../services/redis.yml
- ../../services/smtp-server.yml
- ../../deployments/microservice-product-search-export.yml
- ../../deployments/microservice-product-search.yml
- ../../services/microservice-product-search-export.yml
- ../../services/microservice-product-search.yml
- ../../services/webserver-php-fpm.yml
- ../../deployments/webserver-php-fpm.yml
- ../../ingress.yml
configMapGenerator:
- name: nginx-configuration
  files:
  - ../../../docker/nginx/nginx.conf
- name: postgres-configuration
  files:
  - ../../../docker/postgres/postgres.conf
- name: domains-urls
  files:
  - ../../../app/config/domains_urls.yml
secretGenerator:
- name: gcs-service-account
  commands:
    service-account.json: cd ../../../infrastructure/google-cloud && terraform output shopsys-gcs-service-account-json-key && cd -
