apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shopsys
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "False"
spec:
  rules:
  - host: shop.shopsys.local
    http:
      paths:
      - path: /
        backend:
          serviceName: webserver-php-fpm
          servicePort: 8080
  - host: shop2.shopsys.local
    http:
      paths:
      - path: /
        backend:
          serviceName: webserver-php-fpm
          servicePort: 8080
